config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#home'
  get '/annotation', to: 'welcome#annotation', :as => :annotation
  get '/map/:id', to: 'welcome#map', :as => :map
  post '/sentiment', to: 'welcome#sentiment'

  get '/api/trends', to: 'welcome#trends'
  get '/api/trends/:id', to: 'welcome#stats'
  get '/api/tweets/:id', to: 'welcome#tweets_api'

  get '/api/hashtags', to: 'welcome#hashtags'
  get '/api/hash_tag_trends/:id', to: 'welcome#hash_tag_stats'
  get '/api/hash_tag_tweets/:id', to: 'welcome#hash_tag_tweets'

  get '/all_themes/', to: 'welcome#all_themes' 
  get '/themes/:id', to: 'welcome#themes' 

  get '/form', to: 'data#form'
  get '/countries/:id', to: 'data#countries'
  post '/datasheet', to:'data#datasheet', :as => :data_sheet
  get '/tweets/:time/:country/:id', to: 'data#tweets'
  get '/stats', to: 'data#stats'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :set_tweet, only: [:sentiment]

  def home
  end

  def annotation
    @tweet = Tweet.where(flag: false).sample
    if !@tweet.nil?
      @url = @tweet.url
    end
  end

  def map
    @trend = Trend.current.find params[:id]
    @tweets = @trend.tweets.limit(200)
    @hash = Gmaps4rails.build_markers(@tweets) do |tweet, marker|
      marker.lat tweet.lat
      marker.lng tweet.long
    end

  end

  def sentiment

    if !params[:sentiment].empty? and [-1,1,0,2].include? params[:sentiment].to_i
      @tweet.sentiment = params[:sentiment]
      @tweet.flag = true
      flash[:notice] = "Sentiment lebel applied successfully"
      @tweet.save 
   end

    redirect_to annotation_path

  end

  def trends
    @trends = Trend.current
    @data = {}
    @data[:trends] = []
    @trends.each do |trend|
      @data[:trends] << {name: trend.name, id: trend.id, last_updated_time: trend.updated_at.to_i,
                          start_time: trend.created_at.to_i, 
                          positive: trend.tweets.where(sentiment:0).count,
                          negative: trend.tweets.where(sentiment:-1).count,
                          neutral: trend.tweets.where(sentiment:0).count
                        }
    end

    render json: @data
  end

  def hashtags
    @trends = HashTag.current
    @data = {}
    @data[:trends] = []
    @trends.each do |trend|
      @data[:trends] << {name: trend.name, id: trend.id, last_updated_time: trend.updated_at.to_i,
                          start_time: trend.created_at.to_i,
                          positive: trend.tweets.where(sentiment:0).count,  
                          negative: trend.tweets.where(sentiment:-1).count,
                          neutral: trend.tweets.where(sentiment:0).count
                        }
    end

    render json: @data
  end


  def stats
    @trend = Trend.find params[:id]
    data = {}

    if not @trend.nil?
      data[:sentiment] = {}
      data[:status] = 200

      countries = Tweet.where(tweetable_id: @trend.id).uniq.pluck(:country)

      countries.map do |country|
        if country.nil?
          key = "others"
        else
          key = country
        end
        data[:sentiment][key] = Tweet.where(tweetable_id: @trend.id, country:country).group(:sentiment).count
      end

    else
      data[:status] = 404
      data[:msg] = "Trend with id #{params[:id]} not found"
    end

    render json: data
  end

  def tweets_api
    @trend = Trend.find params[:id]
    data = {}

    if not @trend.nil?
      data[:sentiment] = {}
      data[:status] = 200
      data[:sentiment][:positive] = @trend.tweets.where(sentiment: 1).count
      data[:sentiment][:negative] = @trend.tweets.where(sentiment: -1).count
      data[:sentiment][:neutral] = @trend.tweets.where(sentiment: 0).count

      data[:tweets] = @trend.tweets.page params[:page]
    else
      data[:status] = 404
      data[:msg] = "Trend or HashTag with id #{params[:id]} not found"
    end

    render json: data
  end

  def hash_tag_tweets
    @hash_tag = HashTag.find params[:id]
    data = {}

    if not @hash_tag.nil?
      data[:sentiment] = {}
      data[:status] = 200
      data[:sentiment][:positive] = @hash_tag.tweets.where(sentiment: 1).count
      data[:sentiment][:negative] = @hash_tag.tweets.where(sentiment: -1).count
      data[:sentiment][:neutral] = @hash_tag.tweets.where(sentiment: 0).count

      data[:tweets] = @hash_tag.tweets.page params[:page]
    else
      data[:status] = 404
      data[:msg] = "Trend with id #{params[:id]} not found"
    end

    render json: data
  end

  def hash_tag_stats
    @hash_tag = HashTag.find params[:id]
    data = {}

    if not @hash_tag.nil?
      data[:sentiment] = {}
      data[:status] = 200

      countries = Tweet.where(tweetable_id: @hash_tag.id).uniq.pluck(:country)

      countries.map do |country|
        if country.nil?
          key = "others"
        else
          key = country
        end
        data[:sentiment][key] = Tweet.where(tweetable_id:@hash_tag.id, country:country).group(:sentiment).count
      end

    else
      data[:status] = 404
      data[:msg] = "HashTag with id #{params[:id]} not found"
    end

    render json: data
  end

  def themes

    @hash_tag = HashTag.find params[:id]
    countries = Tweet.where(tweetable_id: @hash_tag.id).uniq.pluck(:country)
    @countries = []

    countries.each_with_index do |country, index|
      @countries[index] = {}
      @countries[index]['name'] = country
      @countries[index]['volume'] = @hash_tag.tweets.where(country:country).count
      @countries[index]['positive'] = @hash_tag.tweets.where(country:country, sentiment: 1).count
      @countries[index]['negative'] = @hash_tag.tweets.where(country:country, sentiment: -1).count
      @countries[index]['neutral'] = @hash_tag.tweets.where(country:country, sentiment: 0).count
    end

  end

  def all_themes
    @hash_tags = HashTag.all
  end

  private
    def set_tweet
      if Tweet.exists?(id: params[:tweet])
        @tweet = Tweet.find params[:tweet]
      else
        redirect_to root_path
      end
    end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/all_themes.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Sentiment Analysis</h3>
          <nav class="nav nav-masthead">
            <a class="nav-link active" href="#">Home</a>
            <a class="nav-link" href="<%= annotation_path%>">Annotator</a>
            <a class="nav-link" href="/all_themes/">Themes</a>

            <a class="nav-link" href="#">Contact</a>
          </nav>
        </div>
      </div>

      <div class="inner cover">
        <p style="text-align: left;"> <small>@hash_tag.name</small></p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Theme Name</th>
              <th>View Stats</th>

            </tr>
          </thead>
          <tbody>
            <% @hash_tags.each do |hash_tag| %>
            <tr>
              <td><%= hash_tag.name %></td>
              <td><a href="/themes/<%=hash_tag.id%>">View Stats</a></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p>Copyright © <a href="www.intelindexer.com"> IntelIndexer</a> 2016 </p>
        </div>
      </div>

    </div>

  </div>

</div>

app/views/welcome/annotation.html.erb
<div class="pos-f-t">

  <nav class="navbar navbar-light navbar-static-top bg-faded">
    <div class="container">
      <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
        &#9776;
      </button>
      <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
        <a class="navbar-brand" href="<%= root_path %>">Tweet Sentiment Analysis</a>
        <!--<ul class="nav navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Nav item <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Another nav item</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">More nav</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Last link</a>
          </li>
        </ul>-->
      </div>
    </div>
  </nav>
</div>

<!-- Begin page content -->

<div class="container">
      <h1>Read tweet and label it</h1>

  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-5" style="color:white">
      <h1>Read tweet and label it</h1>
    </div>
  </div>

  <% if !flash[:notice].nil? %>
    <div class="row">
      <div class="col-md-3">
      </div>

      <div class="col-md-5">
        <div class="alert alert-success" role="alert">
          <strong>Well done!</strong> <%= flash[:notice] %>
        </div>
      </div> 
    
    </div>
  <% end %>


  <% if !@url.nil? %>
    <div class="row">
      <div class="col-md-3">
        <a href="<%= annotation_path %>" style="color: inherit;">
          <i class="fa fa-arrow-left fa-2x pull-right" style="position:relative; top:80px;"></i>
        </a>
      </div>
      <div class="col-md-5">
        <blockquote class="twitter-tweet"><a href="<%= @url %>"></a></blockquote>
        <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
      <div class="col-md-2">
        <a href="<%= annotation_path %>" style="color: inherit;">
          <i class="fa fa-arrow-right fa-2x pull-left" style="position:relative; top:80px;"></i>
        </a>
      </div>

    </div>
    <br/>
    <form action="/sentiment" method="post">
    <%= form_for '', :url => '/sentiment', :authenticity_token => true do |f| %>
      <input type="hidden" name="tweet" value="<%= @tweet.id%>">
      <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-1">
          <input type="radio" name="sentiment" value="1"> Positive
        </div>
        <div class="col-md-1">
          <input type="radio" name="sentiment" value="-1"> Negative
        </div>
        <div class="col-md-1">
          <input type="radio" name="sentiment" value="0"> Neutral
        </div>
        <div class="col-md-1">
          <input type="radio" name="sentiment" value="2"> Ignore
        </div>


      </div>
      <br/>
      <div class="row">
        <div class="col-md-5">   
        </div>
        <div class="col-md-4">
        <button class="btn-primary" name="submit" type="submit" >Submit</button>
        </div>
      </div>
  <% end %>
    <% else %>
        <p class="lead">All available tweets has been lebled. Thank You</p> 
    <% end %>

</div>

<footer class="footer">
  <div class="container" >
    <span class="text-muted">Contact us at saurabh@intelindexer.com</span>
  </div>
</footer>

app/views/welcome/home.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Sentiment Analysis</h3>
          <nav class="nav nav-masthead">
            <a class="nav-link active" href="#">Home</a>
            <a class="nav-link" href="<%= annotation_path%>">Annotator</a>
            <a class="nav-link" href="/all_themes/">Themes</a>

            <a class="nav-link" href="#">Contact</a>
          </nav>
        </div>
      </div>

      <div class="inner cover">
        <p style="text-align: left;"> <small>Trends updated at </small></p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Rank</th>
              <th>Name</th>
              <th>Tweets</th>
              <th>Positive</th>
              <th>Nagative</th>
              <th>Neutral</th>
              <th>Map</th>

            </tr>
          </thead>
          <tbody>
            <%Trend.current.each_with_index do |trend, index|%>
            <tr>
              <td><%= index +1 %></td>
              <td><%= trend.name%></td>
              <td><%= trend.tweets.count%></td>
              <td><%= trend.positive %></td>
              <td><%= trend.negative %></td>
              <td><%= trend.neutral %></td>
              <td><a href="<%= map_path(trend.id) %>"><i class="fa fa-globe"></i></a></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p>Copyright © <a href="www.intelindexer.com"> IntelIndexer</a> 2016 </p>
        </div>
      </div>

    </div>

  </div>

</div>

app/views/welcome/map.html.erb
    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 90%;
      }
      #floating-panel {
        position: absolute;
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }
      #floating-panel {
        background-color: #fff;
        border: 1px solid #999;
        left: 25%;
        padding: 5px;
        position: absolute;
        top: 10px;
        z-index: 5;
      }
    </style>
  </head>



   <div id="map"></div>

    
    <script>

      var map, heatmap;
      var markers = [];

      var data = <%=raw @hash.to_json %>;
      debugger;

      function initMap() {

        var mapOptions = {
          center: new google.maps.LatLng(0, 0),
          zoom: 2,
          minZoom: 1,
          mapTypeId: 'satellite'
        };

        var map = new google.maps.Map(document.getElementById('map'),mapOptions );

        var allowedBounds = new google.maps.LatLngBounds(
          new google.maps.LatLng(85, -180), // top left corner of map
          new google.maps.LatLng(-85, 180)  // bottom right corner
        );

    for (var i = 0; i < data.length; i++) {
      addMarker({ lat: parseFloat(data[i].lat), lng: parseFloat(data[i].lng) }, map);
    }

      }

      function toggleHeatmap() {
        heatmap.setMap(heatmap.getMap() ? null : map);
      }

      function changeGradient() {
        var gradient = [
          'rgba(0, 255, 255, 0)',
          'rgba(0, 255, 255, 1)',
          'rgba(0, 191, 255, 1)',
          'rgba(0, 127, 255, 1)',
          'rgba(0, 63, 255, 1)',
          'rgba(0, 0, 255, 1)',
          'rgba(0, 0, 223, 1)',
          'rgba(0, 0, 191, 1)',
          'rgba(0, 0, 159, 1)',
          'rgba(0, 0, 127, 1)',
          'rgba(63, 0, 91, 1)',
          'rgba(127, 0, 63, 1)',
          'rgba(191, 0, 31, 1)',
          'rgba(255, 0, 0, 1)'
        ]
        heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
      }

      function changeRadius() {
        heatmap.set('radius', heatmap.get('radius') ? null : 20);
      }

      function changeOpacity() {
        heatmap.set('opacity', heatmap.get('opacity') ? null : 0.9);
      }

      var infowindow;
      function addMarker(location, map) {
        var marker = new google.maps.Marker({
          animation: google.maps.Animation.DROP,
          position: location,
          map: map
        });


        markers.push(marker);
      }

    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDGHLVi14Ia8Tp73Zvmfa6O0o8fVry3dz4&libraries=visualization&callback=initMap">
    </script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

app/views/welcome/themes.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Sentiment Analysis</h3>
          <nav class="nav nav-masthead">
            <a class="nav-link active" href="#">Home</a>
            <a class="nav-link" href="<%= annotation_path%>">Annotator</a>
            <a class="nav-link" href="/all_themes/">Themes</a>

            <a class="nav-link" href="#">Contact</a>
          </nav>
        </div>
      </div>

      <div class="inner cover">
        <p style="text-align: left;"> <small>@hash_tag.name</small></p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Conutry</th>
              <th>Positive</th>
              <th>Negative</th>
              <th>Neutral</th>
              <th>Total Volume</th>
            </tr>
          </thead>
          <tbody>
            <% @countries.each do |country| %>
            <tr>
              <td><%=  if !country["name"].nil? then country["name"] else "None" end%></td>
              <td><%= country["positive"] %></td>
              <td><%= country["negative"] %></td>
              <td><%= country["neutral"] %></td>
              <td><%= country["volume"] %></td>

            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p>Copyright © <a href="www.intelindexer.com"> IntelIndexer</a> 2016 </p>
        </div>
      </div>

    </div>

  </div>

</div>